# ===============================
# BASE ORIGEN: cnpv_data
# ===============================
db.origen.url=jdbc:mysql://127.0.0.1:3306/cnpv_data?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Tegucigalpa
db.origen.user=root
db.origen.password=$monitoreoINE#___

# ===============================
# BASE DESTINO: censo_monitoreo
# ===============================
db.destino.url=jdbc:mysql://127.0.0.1:3306/censo_monitoreo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Tegucigalpa
db.destino.user=root
db.destino.password=$monitoreoINE#___

# ===============================
# BASE CONTROL: listener_censo_control
# ===============================
db.control.url=jdbc:mysql://127.0.0.1:3306/listener_censo_control?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Tegucigalpa
db.control.user=root
db.control.password=$monitoreoINE#___

# ===============================
# CONFIGURACION DEL POOL
# ===============================
db.pool.maxSize=25
db.pool.minIdle=5
db.pool.connectionTimeout=30000